### ISSUE TITLE
Problem with architecture apple silicon arm64 

### ISSUE THREAD

**Issue by DeHazar** [cleveradssolutions/CAS-iOS#1]
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56'
ld: warning: Could not find or use auto-linked library 'libAppVerificationLibrary'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsPlatformDescription'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsAnalytics'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsLogging'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsBase'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsSDKConfiguration'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsFeatureFlags'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsBaseUI'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsNetworking'
ld: warning: Could not find or use auto-linked framework 'YXMobileAdsDependenciesUmbrella'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibility56", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAdColony in libCASAdColony.a(CASAdColonyProvider.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAdColony in libCASAdColony.a(CASACInterstitial.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAdColony in libCASAdColony.a(CASACBanner.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAdColony in libCASAdColony.a(CASACBidUnit.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAppLovin in libCASAppLovin.a(DiscoveryDelegate.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAppLovin in libCASAppLovin.a(CASAppLovinProvider.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAppLovin in libCASAppLovin.a(MAXInterstitialAgent.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAdColony, __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASUnityAds , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CleverAdsSolutions , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASTapjoy , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASVungle , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASGoogleAds , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAppLovin , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASIronSource , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASInMobi , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASPangle , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASDigitalTurbine , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASMyTarget , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASMintegral , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASChartboost , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASYandexAds , __swift_FORCE_LOAD_$_swiftCompatibility56_$_CASAudienceNetwork )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Str4tos** [comment]
Hello. 
Please check your XCode version. Minimum supported Xcode version is 14.3 for CAS 3.2.

Let me know if the error is not related to the XCode version.
Thanks for your feedback.
